### ISSUE TITLE
Running tests yields errors

### ISSUE THREAD

**Issue by jh3y** [nearform/graphql-hooks#68]
### Environment

- `graphql-hooks` version: 3.1.1
- `react` version: 16.8.3
- Browser: N/A

### Description
Running `npm run test` yields several errors although the tests pass.

```
Warning: An update to TestHook inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
```

I believe the errors are printed when running `useQuery.test.js` and `useClientRequest.test.js`.

### How to reproduce

```shell
npm run test
```

### Suggested solution (optional)
- Potential versioning issue?

**Comment by jackdclark** [comment]
This was introduced in https://github.com/nearform/graphql-hooks/pull/32. [I've added a comment explaining what the issue is in the test file](https://github.com/nearform/graphql-hooks/blob/master/test/unit/useClientRequest.test.js#L90-L109) but we're waiting to see what happens with this react issue https://github.com/facebook/react/issues/14769.

**Comment by threepointone** [comment]
we just released an alpha with async `act()` implementation that should solve these issues (assuming you were having trouble with an async test). the link in your comment doesn't work anymore? lemme know if you have issues with the alpha, and I'd be happy to pitch in and help fix it.

**Comment by bmullan91** [comment]
@threepointone ah the comment link got lost after the lerna move. Here it is: https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/test/unit/useClientRequest.test.js#L262-L281

Great work on https://github.com/facebook/react/pull/14853 btw - I've just tried `16.9.0-alpha.0` locally and all the big scary`Warning: An update to TestHook inside a test was not wrapped in act(...).` logs are gone 🎉

**Comment by bmullan91** [comment]
Fixed in #412

**Comment by nuragic** [comment]
We still have this console errors when running unit tests: `Warning: An update to TestComponent inside a test was not wrapped in act(...).`

I've also found that in #604 @salmanm talk about this warnings and suggest that the proposed solution would avoid them.
